### ISSUE TITLE
A flaky test: `connectors::grpc::tests::ingest_grpc_default`

### ISSUE THREAD

**Issue by xudong963** [getdozer/dozer#1139]
```
failures:

---- connectors::grpc::tests::ingest_grpc_default stdout ----
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InitializationError("transport error")', dozer-ingestion/src/connectors/grpc/tests.rs:47:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'connectors::grpc::tests::ingest_grpc_default' panicked at 'failed to connect after 9 times', dozer-ingestion/src/connectors/grpc/tests.rs:58:13
```

https://github.com/getdozer/dozer/actions/runs/4335159786/jobs/7569537556

**Comment by xudong963** [comment]
Seems related to https://github.com/getdozer/dozer/pull/1087 .  cc @v3g42
